# Generated by Django 3.0.2 on 2022-01-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0003_auto_20220115_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_grade_level',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
