# Generated by Django 2.0.7 on 2022-01-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0004_student_student_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_address',
            field=models.CharField(default='cityx', max_length=300),
        ),
        migrations.AddField(
            model_name='student',
            name='student_dislikes',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_hobbies',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_likes',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_middlename',
            field=models.CharField(default='middlename', max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='student_nationality',
            field=models.CharField(default='No nationality', max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='student_nickname',
            field=models.CharField(default='nickname', max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='student_religion',
            field=models.CharField(default='None', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_telno',
            field=models.CharField(default='None', max_length=128),
        ),
    ]
