# Generated by Django 2.2 on 2022-01-23 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0005_auto_20220118_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_s_account_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sis_app.Student')),
                ('paymentdate_date', models.DateField()),
                ('payment_amount', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('sis_app.student',),
        ),
    ]
