# Generated by Django 3.0.2 on 2022-01-24 06:34

import datetime
import django.core.validators
from django.db import migrations, models
import sis_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0005_auto_20220118_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_telno',
        ),
        migrations.AddField(
            model_name='student',
            name='student_accuracy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='student_allergies',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='student_birthday',
            field=models.DateField(default=datetime.date(2022, 1, 24)),
        ),
        migrations.AddField(
            model_name='student',
            name='student_f_address',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='student',
            name='student_f_employer',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='student_f_firstname',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='student_f_lastname',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='student_f_middlename',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='student_f_natureofbusiness',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='student_f_oaddress',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='student',
            name='student_f_occupation',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='student_f_otelno',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='student_f_telno',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='student_guardianemail',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='student_m_address',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='student',
            name='student_m_employer',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='student_m_firstname',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='student_m_lastname',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='student_m_middlename',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='student_m_natureofbusiness',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='student_m_oaddress',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='student',
            name='student_m_occupation',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='student_m_otelno',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='student_m_telno',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='student_medexp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='student_oconsiderations',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='student_rules',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='student_sd',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='student_shm',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='student_sibling_age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='student_sibling_gender',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='student_sibling_name',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='student',
            name='student_sibling_school',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='student',
            name='student_signdate',
            field=models.DateField(default=datetime.date(2022, 1, 24)),
        ),
        migrations.AddField(
            model_name='student',
            name='student_signedname',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_address',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_dislikes',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_firstname',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_grade_level',
            field=models.CharField(choices=[('Nursery', 'Nursery'), ('Kinder 1', 'Kinder 1'), ('Kinder 2', 'Kinder 2')], default='Nursery', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_hobbies',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_lastname',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_likes',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_middlename',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_nationality',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_nickname',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_religion',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_schoolyear_start',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(2000), sis_app.models.max_value_current_year], verbose_name='year'),
        ),
    ]
