# Generated by Django 2.2 on 2022-01-26 13:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0006_auto_20220124_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_birthday',
            field=models.DateField(default=datetime.date(2022, 1, 26)),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_signdate',
            field=models.DateField(default=datetime.date(2022, 1, 26)),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentdate_date', models.DateField()),
                ('payment_amount', models.IntegerField()),
                ('outstandingbalance', models.IntegerField(default=37999)),
                ('tuitionfee', models.IntegerField(default=50000)),
                ('payment_s_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_app.Student')),
            ],
        ),
    ]
