# Generated by Django 2.2 on 2022-01-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0006_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
