# Generated by Django 2.2 on 2022-01-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0007_student_payment_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='payment_plan',
        ),
        migrations.AddField(
            model_name='student',
            name='student_payment_plan',
            field=models.CharField(choices=[('Annually', 'Annually'), ('Bi-Annually', 'Bi-Annually'), ('Quarterly', 'Quarterly')], default='Annually', max_length=20),
        ),
    ]
