# Generated by Django 2.2 on 2022-01-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_plan',
            field=models.CharField(choices=[('Annually', 'Annually'), ('Bi-Annually', 'Bi-Annually'), ('Quarterly', 'Quarterly')], default='Annually', max_length=20),
        ),
    ]
