# Generated by Django 2.2 on 2022-01-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0009_student_enrollment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='outstandingbalance',
            field=models.IntegerField(default=1000),
        ),
    ]
