# Generated by Django 2.2 on 2022-01-29 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0010_auto_20220128_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='tuitionfee',
        ),
        migrations.AlterField(
            model_name='payment',
            name='outstandingbalance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_birthday',
            field=models.DateField(default=datetime.date(2022, 1, 29)),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_signdate',
            field=models.DateField(default=datetime.date(2022, 1, 29)),
        ),
    ]
