# Generated by Django 2.2 on 2022-01-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0010_payment_outstandingbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tuitionfee',
            field=models.IntegerField(default=50000),
        ),
        migrations.AlterField(
            model_name='payment',
            name='outstandingbalance',
            field=models.IntegerField(default=50000),
        ),
    ]
