# Generated by Django 2.2 on 2022-01-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0011_auto_20220126_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='outstandingbalance',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tuitionfee',
        ),
    ]
