# Generated by Django 3.0.2 on 2022-02-09 13:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0011_auto_20220129_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptOfRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tor_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='student_birthday',
            field=models.DateField(default=datetime.date(2022, 2, 9)),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_signdate',
            field=models.DateField(default=datetime.date(2022, 2, 9)),
        ),
        migrations.CreateModel(
            name='GradeReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_grade', models.IntegerField()),
                ('mathematics_grade', models.IntegerField()),
                ('language_grade', models.IntegerField()),
                ('science_grade', models.IntegerField()),
                ('penmanship_grade', models.IntegerField()),
                ('filipino_grade', models.IntegerField()),
                ('tor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_app.TranscriptOfRecord')),
            ],
        ),
    ]
