# Generated by Django 3.0.2 on 2022-02-09 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0012_auto_20220209_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradereport',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sis_app.Student'),
        ),
    ]
