# Generated by Django 2.2 on 2022-01-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0012_auto_20220126_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='outstandingbalance',
            field=models.IntegerField(default=50000),
        ),
        migrations.AddField(
            model_name='payment',
            name='tuitionfee',
            field=models.IntegerField(default=50000),
        ),
    ]
