# Generated by Django 3.0.2 on 2022-02-09 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0013_gradereport_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptofrecord',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sis_app.Student'),
        ),
    ]
