# Generated by Django 3.0.2 on 2022-02-09 16:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0014_transcriptofrecord_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradereport',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_app.Student'),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='tor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_app.TranscriptOfRecord'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_birthday',
            field=models.DateField(default=datetime.date(2022, 2, 10)),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_signdate',
            field=models.DateField(default=datetime.date(2022, 2, 10)),
        ),
        migrations.AlterField(
            model_name='transcriptofrecord',
            name='tor_id',
            field=models.IntegerField(default=0),
        ),
    ]
