# Generated by Django 3.0.2 on 2022-02-09 16:52

import django.core.validators
from django.db import migrations, models
import sis_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0015_auto_20220210_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradereport',
            name='grading_period',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='school_year',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(2000), sis_app.models.max_value_current_year], verbose_name='year'),
        ),
    ]
