# Generated by Django 2.2 on 2022-02-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0018_auto_20220211_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradereport',
            name='filipino_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='language_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='mathematics_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='penmanship_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='reading_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='science_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
