# Generated by Django 2.2 on 2022-02-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0020_auto_20220212_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradereport',
            name='sem_average',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
