# Generated by Django 2.2 on 2022-02-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0023_auto_20220213_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradereport',
            name='final_filipino',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='final_language',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='final_mathematics',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='final_penmanship',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='final_reading',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='final_science',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
