# Generated by Django 2.2 on 2022-02-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0024_auto_20220213_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradereport',
            name='absences',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='school_days',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
