# Generated by Django 3.0.2 on 2022-02-15 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0025_auto_20220213_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='outstandingbalance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_birthday',
            field=models.DateField(default=datetime.date(2022, 2, 15)),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_signdate',
            field=models.DateField(default=datetime.date(2022, 2, 15)),
        ),
    ]
