# Generated by Django 3.0.2 on 2022-02-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0026_auto_20220215_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='outstandingbalance',
            field=models.IntegerField(default=None),
        ),
    ]
