# Generated by Django 3.0.2 on 2022-02-15 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0030_auto_20220215_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradereport',
            name='school_year',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(2000)], verbose_name='year'),
        ),
    ]
