# Generated by Django 3.0.2 on 2022-02-15 09:49

import django.core.validators
from django.db import migrations, models
import sis_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0032_auto_20220215_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradereport',
            name='school_year',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(2000), sis_app.models.max_value_current_year], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_schoolyear_start',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(2000)], verbose_name='year'),
        ),
    ]
