# Generated by Django 3.0.2 on 2022-02-15 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0033_auto_20220215_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='school_year_end',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(2000)], verbose_name='year'),
        ),
    ]
