# Generated by Django 2.2 on 2022-02-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0013_auto_20220209_0103'),
        ('sis_app', '0036_payment_school_year_end'),
    ]

    operations = [
    ]
