# Generated by Django 2.2 on 2022-02-19 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0037_merge_20220219_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradereport',
            name='gr_acknowledgement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_birthday',
            field=models.DateField(default=datetime.date(2022, 2, 19)),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_signdate',
            field=models.DateField(default=datetime.date(2022, 2, 19)),
        ),
    ]
