# Generated by Django 3.0.2 on 2022-02-24 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0037_merge_20220217_2251'),
        ('sis_app', '0038_auto_20220219_2153'),
    ]

    operations = [
    ]
