# Generated by Django 2.2 on 2022-02-28 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0038_auto_20220219_2153'),
        ('sis_app', '0037_merge_20220217_2251'),
    ]

    operations = [
    ]
