# Generated by Django 2.2 on 2022-02-28 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0039_merge_20220228_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradereport',
            name='N_creative_domain',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_creative_domain1',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_creative_domain2',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_creative_domain3',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_creative_domain4',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_creative_domain5',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_good_moral_valueformation',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_good_moral_valueformation1',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_good_moral_valueformation2',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_good_moral_valueformation3',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_good_moral_valueformation4',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_good_moral_valueformation5',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_good_moral_valueformation6',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_good_moral_valueformation7',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_good_moral_valueformation8',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_good_moral_valueformation9',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_interpersonal_skills',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_interpersonal_skills1',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_interpersonal_skills10',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_interpersonal_skills11',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_interpersonal_skills12',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_interpersonal_skills13',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_interpersonal_skills2',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_interpersonal_skills3',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_interpersonal_skills4',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_interpersonal_skills5',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_interpersonal_skills6',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_interpersonal_skills7',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_interpersonal_skills8',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_interpersonal_skills9',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_language',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_motor_skills',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_motor_skills1',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_motor_skills10',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_motor_skills11',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_motor_skills12',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_motor_skills13',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_motor_skills2',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_motor_skills3',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_motor_skills4',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_motor_skills5',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_motor_skills6',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_motor_skills7',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_motor_skills8',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_motor_skills9',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_number_readiness',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_number_readiness1',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_number_readiness2',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_number_readiness3',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_number_readiness4',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_number_readiness5',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_number_readiness6',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_number_readiness7',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_number_readiness8',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_reading_readiness',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_reading_readiness1',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_reading_readiness10',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_reading_readiness11',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_reading_readiness12',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_reading_readiness13',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_reading_readiness2',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_reading_readiness3',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_reading_readiness4',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_reading_readiness5',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_reading_readiness6',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_reading_readiness7',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_reading_readiness8',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_reading_readiness9',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_science',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_science1',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_science2',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_science3',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_science4',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_science5',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_science6',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='Nlanguage1',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='Nlanguage10',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='Nlanguage2',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='Nlanguage3',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='Nlanguage4',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='Nlanguage5',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='Nlanguage6',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='Nlanguage7',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='Nlanguage8',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='Nlanguage9',
            field=models.CharField(choices=[('O', 'O'), ('VG', 'VG'), ('G', 'G'), ('F', 'F')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_birthday',
            field=models.DateField(default=datetime.date(2022, 2, 28)),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_signdate',
            field=models.DateField(default=datetime.date(2022, 2, 28)),
        ),
    ]
