# Generated by Django 2.2 on 2022-02-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0041_auto_20220228_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_grade_level',
            field=models.CharField(choices=[('Nursery', 'Nursery'), ('Kinder 1', 'Kinder 1'), ('Kinder 2 Junior', 'Kinder 2 Junior'), ('Kinder 2 Senior', 'Kinder 2 Senior')], default='Nursery', max_length=128),
        ),
    ]
