# Generated by Django 2.2 on 2022-02-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0042_auto_20220228_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradereport',
            name='N_final_creative_domain',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_final_good_moral_valueformation',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_final_interpersonal_skills',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_final_language',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_final_motor_skills',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_final_number_readiness',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_final_reading_readiness',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='gradereport',
            name='N_final_science',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
