# Generated by Django 2.2 on 2022-02-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0044_auto_20220228_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradereport',
            name='N_final_creative_domain',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='N_final_good_moral_valueformation',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='N_final_interpersonal_skills',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='N_final_language',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='N_final_motor_skills',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='N_final_number_readiness',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='N_final_reading_readiness',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='N_final_science',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
