# Generated by Django 2.2 on 2022-02-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0045_auto_20220228_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradereport',
            name='N_year_average',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
