# Generated by Django 3.0.2 on 2022-03-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0046_gradereport_n_year_average'),
        ('sis_app', '0040_auto_20220224_0905'),
    ]

    operations = [
    ]
