# Generated by Django 2.2 on 2022-03-01 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0040_auto_20220224_0905'),
        ('sis_app', '0046_gradereport_n_year_average'),
    ]

    operations = [
    ]
