# Generated by Django 2.2 on 2022-03-01 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0047_merge_20220301_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradereport',
            name='gradelevel',
            field=models.CharField(choices=[('Nursery', 'Nursery'), ('Kinder 1', 'Kinder 1'), ('Kinder 2 Junior', 'Kinder 2 Junior'), ('Kinder 2 Senior', 'Kinder 2 Senior')], default='Nursery', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_birthday',
            field=models.DateField(default=datetime.date(2022, 3, 1)),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_signdate',
            field=models.DateField(default=datetime.date(2022, 3, 1)),
        ),
    ]
