# Generated by Django 2.2 on 2022-03-09 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0048_auto_20220301_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradereport',
            name='gr_acknowledgement',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_birthday',
            field=models.DateField(default=datetime.date(2022, 3, 9)),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_signdate',
            field=models.DateField(default=datetime.date(2022, 3, 9)),
        ),
    ]
