# Generated by Django 2.2 on 2022-03-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0049_auto_20220309_1121'),
        ('sis_app', '0049_auto_20220309_1853'),
    ]

    operations = [
    ]
