# Generated by Django 2.2 on 2022-03-20 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0050_merge_20220320_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradereport',
            name='gr_acknowledgement',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_birthday',
            field=models.DateField(default=datetime.date(2022, 3, 20)),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_signdate',
            field=models.DateField(default=datetime.date(2022, 3, 20)),
        ),
    ]
