# Generated by Django 3.0.2 on 2022-03-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0051_auto_20220320_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradereport',
            name='school_year',
            field=models.IntegerField(choices=[(2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)], default=2022),
        ),
    ]
