# Generated by Django 3.0.2 on 2022-03-21 16:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0054_auto_20220321_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentdate_date',
            field=models.DateField(default=datetime.date(2022, 3, 22)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='school_year_end',
            field=models.IntegerField(default=None, error_messages={'invalid': 'Invalid'}, validators=[django.core.validators.MinValueValidator(2000)], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_birthday',
            field=models.DateField(default=datetime.date(2022, 3, 22)),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_signdate',
            field=models.DateField(default=datetime.date(2022, 3, 22)),
        ),
    ]
