# Generated by Django 3.0.2 on 2022-03-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0055_auto_20220322_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toggle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toggleReg', models.BooleanField(default=True)),
            ],
        ),
    ]
