# Generated by Django 3.0.2 on 2022-03-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0057_auto_20220323_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradereport',
            name='gradelevel',
            field=models.CharField(choices=[('Nursery', 'Nursery'), ('Kinder 1', 'Kinder 1'), ('Kinder 2 Junior', 'Kinder 2 Junior'), ('Kinder 2 Senior', 'Kinder 2 Senior')], default='Nursery', max_length=30),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='gr_acknowledgement',
            field=models.BooleanField(default=False),
        ),
    ]
