# Generated by Django 3.0.2 on 2022-03-26 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0060_auto_20220326_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_s_account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_app.Student'),
        ),
    ]
