# Generated by Django 3.0.2 on 2022-03-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0061_auto_20220326_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='school_year_end',
            field=models.IntegerField(null=True, verbose_name='year'),
        ),
    ]
