# Generated by Django 3.0.2 on 2022-03-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0063_auto_20220328_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_schoolyear_start',
            field=models.IntegerField(choices=[(2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034)], default=None),
        ),
    ]
