# Generated by Django 3.0.2 on 2022-03-28 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0065_auto_20220328_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='enrollment_type',
            field=models.CharField(default='Annually', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentdate_date',
            field=models.DateField(default=datetime.date(2022, 3, 29)),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_birthday',
            field=models.DateField(default=datetime.date(2022, 3, 29)),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_signdate',
            field=models.DateField(default=datetime.date(2022, 3, 29)),
        ),
    ]
