# Generated by Django 2.2 on 2022-03-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0065_auto_20220328_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='enrollment_type',
            field=models.CharField(default='Annually', max_length=20),
        ),
    ]
