# Generated by Django 3.0.2 on 2022-03-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0068_auto_20220329_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradereport',
            name='sem_average',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='year_average',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
