# Generated by Django 3.0.2 on 2022-03-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0070_auto_20220330_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='header',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcement',
            field=models.CharField(default=None, max_length=1500),
        ),
    ]
