# Generated by Django 3.0.2 on 2022-03-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0071_auto_20220330_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement',
            field=models.TextField(default=None, max_length=1500),
        ),
    ]
