# Generated by Django 2.2 on 2022-04-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0074_merge_20220401_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_sibling_gender',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
