# Generated by Django 3.0.2 on 2022-04-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0074_merge_20220401_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradereport',
            name='gradelevel',
        ),
    ]
