# Generated by Django 2.2 on 2022-04-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0075_auto_20220401_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_f_natureofbusiness',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_f_otelno',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_likes',
            field=models.TextField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_m_natureofbusiness',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_m_otelno',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_oconsiderations',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_religion',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_sibling_age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_sibling_name',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_sibling_school',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
