# Generated by Django 2.2 on 2022-04-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0076_auto_20220401_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_likes',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
