# Generated by Django 2.2 on 2022-04-14 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0076_auto_20220401_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentdate_date',
            field=models.DateField(default=datetime.date(2022, 4, 14)),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_birthday',
            field=models.DateField(default=datetime.date(2022, 4, 14)),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_signdate',
            field=models.DateField(default=datetime.date(2022, 4, 14)),
        ),
    ]
