# Generated by Django 2.2 on 2022-04-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0077_auto_20220401_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_dislikes',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
