# Generated by Django 2.2 on 2022-04-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0077_auto_20220414_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_account_generated',
            field=models.BooleanField(default=False),
        ),
    ]
