# Generated by Django 3.0.2 on 2022-04-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_app', '0079_auto_20220415_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradereport',
            name='gradelevel',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
